<FlatButton@ButtonBehavior+Label>:
    font_size: 16

<SmoothButton@Button>:
    background_color: (0,0,0,0)
    background_normal: ''
    back_color: (1,0,1,1)
    border_radius: [20]
    canvas.before:
        Color:
            rgba: self.back_color
        # Line:
        #     rounded_rectangle: (self.pos[0], self.pos[1], self.size[0], self.size[1], self.border_radius)
        #     width: 1.2

        RoundedRectangle:
            size: self.size
            pos: self.pos
            #radius: self.border_radius
        


<SigninWindow>:
    id: main_win
    orientation: "vertical"
    space_x: self.size[0]/3
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    
    BoxLayout:
        size_hint_y: None
        height: 45
        canvas.before:
            Color:
                rgba: (77/255.0,77/255.0,77/255.0,255/255.0)
            Rectangle:
                size: self.size
                pos: self.pos

        Label:
            text: "Inicio de Sesión"
            bold: True
            size_hint_x: .9


        FlatButton:
            text: "x"
            size_hint_x: .1


    BoxLayout:
        orientation: "vertical"
        padding: main_win.space_x, 10

        BoxLayout:
            orientation: "vertical"
            spacing: 10
            size_hint_y: None
            height: 200
            Image:
                source: 'Logo.png'
                size: self.size

        BoxLayout:
            orientation: "vertical"
            spacing: 10
            size_hint_y: None
            height: 100
            Label:
                id: info
                text: ''
                markup: True
                size_hint_y: None
                height: 20
            TextInput:
                id: username_field
                hint_text: "Usuario"
                multiline: False
                focus: True
                on_text_validate: pwd_field.focus = True
            TextInput:
                id: pwd_field
                hint_text: "Contraseña"
                multiline: False
                password: True
                on_text_validate: root.validate_user()
                spacing: 20


        Label:
            id: sp
            size_hint_y: 10

        SmoothButton:
            text: "Iniciar Sesion"
            size_hint_y: None
            size_hint_x: .5
            pos_hint: {'x':.25, 'y':.2}
            height: 40
            back_color: (0/255.0,113/255.0,183/255.0,255/255.0)
            on_release: root.validate_user()
            bold: True
        Label:
            id: sp2
            size_hint_y: 200
